Source/ManagementTools/ControlCenter/BadumnaNetworkController/Controllers/PackageBuilderController.cs
//---------------------------------------------------------------------------------
// <copyright file="PackageBuilderController.cs" company="National ICT Australia Pty Ltd">
//     Copyright (c) 2010 National ICT Australia Pty Ltd. All rights reserved.
// </copyright>
//---------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

using BadumnaNetworkController.Models;

using Germinator;
using Germinator.PrestoManifesto;

namespace BadumnaNetworkController.Controllers
{
    /// <summary>
    /// PackageBuilder controller has the same functionality as PrestoManifesto application to build packages for services 
    /// that run in the ControlCenter (Note : application and service are the same in this context).
    /// </summary>
    public class PackageBuilderController : Controller
    {
        /// <summary>
        /// List of the current available applications on PrestoManifesto.
        /// </summary>
        private static Dictionary<string, PrestoManifesto> applicationList = new Dictionary<string, PrestoManifesto>();

        /// <summary>
        /// ProcessTask delegate used to start asycn package build process.
        /// </summary>
        /// <param name="applicationName">Service name.</param>
        /// <param name="description">Package description.</param>
        /// <returns>Return the service name.</returns>
        private delegate string ProcessTask(string applicationName, string description);

        /// <summary>
        /// PackageBuilder index page, displaying all available services in the current project file.
        /// </summary>
        /// <returns>Retrun the PackageBuilder index page.</returns>
        public ActionResult Index()
        {
            // get the list of applications
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;

            if (configuration != null && configuration.PrestoManifestoProject != null)
            {
                this.ViewData.Model = configuration.PrestoManifestoProject.Applications.AsEnumerable();
            }

            return View();
        }

        /// <summary>
        /// Add a new service to the current project.
        /// </summary>
        /// <returns>Return AddService.aspx page.</returns>
        public ActionResult AddService()
        {
            ViewData.Model = (IEnumerable<string>)Enum.GetNames(typeof(ServiceType));
            return View();
        }

        /// <summary>
        /// Post method of AddService, get the service name from the user and use it to create a new service and 
        /// add it to the current project.
        /// </summary>
        /// <param name="name">Service Name.</param>
        /// <param name="type">Service type.</param>
        /// <returns>Redirect to PackageBuilder index page.</returns>
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AddService(string name, string type)
        {
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;

            try
            {
                if (string.IsNullOrEmpty(name))
                {
                    this.ModelState.AddModelError("name", Resources.MustGiveName);
                }

                IEnumerable<PackageData> packages = configuration.PrestoManifestoProject.Applications.AsEnumerable();
                foreach (PackageData package in packages)
                {
                    if (package.Name.Equals(name))
                    {
                        this.ModelState.AddModelError("name", Resources.NameInUse);
                    }
                }

                if (!InputValidationHelper.ValidateAlphanumeric(name))
                {
                    this.ModelState.AddModelError("name", Resources.InvalidName);
                }

                if (string.IsNullOrEmpty(type))
                {
                    this.ModelState.AddModelError("type", Resources.MustGivenType);
                }

                if (!this.ModelState.IsValid)
                {
                    ViewData.Model = (IEnumerable<string>)Enum.GetNames(typeof(ServiceType));
                    return View();
                }
            }
            catch (Exception)
            {
                return View();
            }

            if (configuration != null)
            {
                string appPath = Request.PhysicalApplicationPath;
                string saveDir = string.Empty;
                if (!configuration.IsMono)
                {
                    saveDir = @"Packages\";
                }
                else
                {
                    saveDir = @"Packages/";
                }

                string fullPath = Path.Combine(appPath, saveDir);
                configuration.AddNewService(name, fullPath, (ServiceType)Enum.Parse(typeof(ServiceType), type, true));
            }

            return RedirectToAction("Details", new { name = name });
        }

        /// <summary>
        /// Remove a particular service based on the given service name.
        /// </summary>
        /// <param name="name">Service name.</param>
        /// <returns>Redirect to PackageBuilder index page.</returns>
        public ActionResult Remove(string name)
        {
            if (this.Request.IsAjaxRequest())
            {
                Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;

                if (configuration != null)
                {
                    configuration.RemoveService(name);

                    // Remove the application from the application list
                    applicationList.Remove(name);

                    return PartialView("List", configuration.PrestoManifestoProject.Applications.AsEnumerable());
                }
            }
         
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Display the details of a particular service name, includes the information about the current version of 
        /// the built package, and all files included for this particular service.
        /// </summary>
        /// <param name="name">Service name.</param>
        /// <returns>Return the Details.aspx page fot a particular service based on the given service name.</returns>
        public ActionResult Details(string name)
        {
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;

            if (configuration != null)
            {
                PrestoManifesto prestoManifesto = null;
                string treeView = string.Empty;

                if (!applicationList.TryGetValue(name, out prestoManifesto))
                {
                    prestoManifesto = new PrestoManifesto();
                    prestoManifesto.Name = name;
                    prestoManifesto.PackageVersion = configuration.GetPackageVersion(name);
                    prestoManifesto.IncludeExtractionTools = configuration.IncludeExtractionTools(name);
                    prestoManifesto.CompleteUpdate = configuration.GetUpdateType(name).Equals("complete");
                    prestoManifesto.Contents = configuration.GetContents(name);
                    prestoManifesto.Executable = configuration.GetExecutable(name);
                    prestoManifesto.BaseDirectory = configuration.GetBaseDirectory(name);

                    this.GenerateTreeViewRecursive(prestoManifesto.Contents, prestoManifesto.BaseDirectory, ref treeView);
                    prestoManifesto.TreeView = treeView;

                    applicationList.Add(name, prestoManifesto);
                }

                // TODO : should fix this, currently it will always check the package version number.
                prestoManifesto.PackageVersion = configuration.GetPackageVersion(name);

                this.ViewBag.name = name;
                this.ViewBag.confName = configuration.Name;
                this.ViewData.Model = prestoManifesto;
            }

            return View();
        }

        /// <summary>
        /// Upload the package from the client side to the server side.
        /// </summary>
        /// <param name="name">Service name.</param>
        /// <param name="config">Current configuration name.</param>
        /// <returns>Redirect to the details for a given sercive name.</returns>
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Upload(string name, string config)
        {
            Configuration configuration = GerminatorFacade.Instance.GetConfiguration(config);
            if (configuration != null)
            {
                string appPath = Request.PhysicalApplicationPath;
                string saveDir = string.Empty;
                if (!configuration.IsMono)
                {
                    saveDir = @"Packages\" + name + @"\";
                }
                else
                {
                    saveDir = @"Packages/" + name + @"/";
                }
                
                HttpFileCollectionBase hfc = Request.Files;
                for (int i = 0; i < hfc.Count; i++)
                {
                    HttpPostedFileBase file = hfc[i];
                    string fileName = file.FileName;
                    
                    if (!Directory.Exists(Path.Combine(appPath, saveDir)))
                    {
                        Directory.CreateDirectory(Path.Combine(appPath, saveDir));
                    }


Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/PackageBuilder/AddService.cshtml
@using System.Collections;
@using BadumnaNetworkController;

@model IEnumerable<string>
@{
    ViewBag.Title = Resources.AddService;
}

<h2>@Resources.AddService<img src="../../Content/images/qm.png" style="width:20px;height:20px;cursor:pointer;" alt="QuestionMark" onclick="showHelp('AddService','Overview');"/></h2>

@Html.ValidationSummary(Resources.ErrorSummary)
@using (Html.BeginForm())
{
    <fieldset>
        <table>
            <tr>
                <td><label for="Name">@Resources.ServiceName</label></td>
                <td>
                    @Html.TextBox("Name", null, new { style = "width:221px;" })
                    @Html.ValidationMessage("Name", "*")
                </td>
            </tr>
            <tr>
                <td><label for="Type">@Resources.ServiceType</label></td>
                <td>
                    @Html.DropDownList("Type", new SelectList(Model))
                    @Html.ValidationMessage("Type", "*")
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" value='@Resources.Create' />
                </td>
            </tr>
        </table>
    </fieldset>
}

<p>
    @Html.ActionLink(Resources.Back, "Index", "PackageBuilder")
</p>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/PackageBuilder/ContentView.cshtml
@using BadumnaNetworkController.Models;

@model PrestoManifesto

<link href="../../Content/Site.css" rel="stylesheet" type="text/css" visible="false"/>
<link href="../../Scripts/jquery-treeview/jquery.treeview.css" rel="Stylesheet" type="text/css" />

<ul id="contentList" class="filetree treeview-famfamfam treeview">
@{
    string projectName = string.Format("{0} Project", Model.Name);
    <li>
        <span id="@Model.BaseDirectory" class="folder" title="Right click to add a file">@Html.Encode(projectName)</span>
	    <ul>
            @Html.RenderHtml(Model.TreeView)
        </ul>
	</li>   
}
</ul>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/PackageBuilder/Index.cshtml
@using System.Collections;
@using Germinator.PrestoManifesto;
@using BadumnaNetworkController;

@model IEnumerable<PackageData>
@{
    ViewBag.Title = Resources.PackageBuilder;
}

<h2>@Resources.CustomServiceBuilder<img src="../../Content/images/qm.png" style="width:20px;height:20px;cursor:pointer;" alt="QuestionMark" onclick="showHelp('PackageBuilder','Overview');"/></h2>
<fieldset>
    <legend>Applications</legend>
    @if (Model != null)
     {
        Html.RenderPartial("List", Model);
     }
</fieldset>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/PackageBuilder/List.cshtml
@using System.Collections;
@using Germinator.PrestoManifesto;
@using BadumnaNetworkController;

@model IEnumerable<PackageData>

<div id="list">
    <table class="generalListTable">
        <tr>
            <th colspan='2'>
                @Resources.ApplicationName:
            </th>
        </tr>
            @if (Model != null && Model.Count<PackageData>() > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.Encode(item.Name)
                        </td>
                        <td align='center'>
                            @Html.ActionLink(Resources.Change, "Details", new { name = item.Name })|
                            @Ajax.ActionLink(
                                Resources.Remove, 
                                "Remove", 
                                new { name = item.Name },
                                new AjaxOptions(){ UpdateTargetId = "list" })
                        </td>
                    </tr>
                }
            }
        <tr>
            <td colspan='2'>
                @Html.ActionLink(Resources.AddService, "AddService", "PackageBuilder")
            </td>
        </tr>   
    </table>
</div>