Source/ManagementTools/ControlCenter/BadumnaNetworkController/Controllers/ComponentController.cs
//-----------------------------------------------------------------------
// <copyright file="ComponentController.cs" company="Scalify Pty Ltd">
//     Copyright (c) 2010 Scalify Pty Ltd. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

using Germinator;
using Germinator.Components;
using Germinator.Services;

namespace BadumnaNetworkController.Controllers
{
    /// <summary>
    /// ComponentController class is used for displaying and modifying the properties for each individual 
    /// components and services that are available in ControlCenter. 
    /// </summary>
    public class ComponentController : Controller
    {
        /// <summary>
        /// Edit the component or service basic properties.
        /// </summary>
        /// <remarks>GET: /Component/Edit?index=service_name</remarks>
        /// <param name="index">Name of the component or service.</param>
        /// <returns>Return the details form contains component or service basic properties.</returns>
        public ActionResult Edit(string index)
        {
            // Checking for any existance of ModelState in temp data.
            if (this.TempData["ModelState"] != null && !this.ModelState.Equals(this.TempData["ModelState"]))
            {
                this.ModelState.Merge((ModelStateDictionary)this.TempData["ModelState"]);
            }

            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;
            if (configuration == null || String.IsNullOrEmpty(index))
            {
                return RedirectToAction("Index", "Home");
            }            

            ComponentView component = configuration.GetComponent(index);
            if (component == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            this.ViewData.Model = component;

            if ((component.Instance as BaseService) == null && configuration.RunningServices.Count > 0)
            {
                this.ViewBag.SettingChangeAllowed = false;
            }
            else
            {
                this.ViewBag.SettingChangeAllowed = true;
            }

            string hostname;
            int port;

            configuration.GetDeiHost(out hostname, out port);

            if (!string.IsNullOrEmpty(hostname))
            {
                this.ViewBag.DeiServerAddress = string.Format("{0}:{1}", hostname, port);
            }
            else
            {
                this.ViewBag.DeiServerAddress = null;
            }

            return View();
        }

        /// <summary>
        /// Post method from the edit component, update the component or service properties using 
        /// the submitted form received.
        /// </summary>
        /// <remarks>POST: /Component/Edit/</remarks>
        /// <param name="name">Name of the component or service.</param>
        /// <param name="isEnabled">This parameter is no longer used.</param>
        /// <param name="collection">The form collection obtained from the client.</param>
        /// <returns>Redirect to Edit action.</returns>
        /// <seealso cref="Edit(string)"/>
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit(string name, bool? isEnabled, FormCollection collection)
        {
            try
            {
                Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;
                if (configuration == null || string.IsNullOrEmpty(name))
                {
                    return RedirectToAction("Index", "Home");
                }
               
                ComponentView componentView = configuration.GetComponent(name);
                if (componentView == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                if (!isEnabled.HasValue)
                {
                    isEnabled = false;
                }

                for (int i = 0; i < collection.Count; i++)
                {
                    if (collection[i] == null)
                    {                        
                        this.ModelState.AddModelError(collection.GetKey(i), Resources.Invalid);
                    }

                    // extra checking for application name.
                    if (collection.GetKey(i) == "ApplicationName")
                    {
                        if (!InputValidationHelper.ValidateAlphanumeric(collection[i] as string))
                        {
                            this.ModelState.AddModelError(collection.GetKey(i), Resources.InvalidName);
                        }
                    }
                }

                if (!this.ModelState.IsValid)
                {
                    this.TempData["ModelState"] = this.ModelState;
                    return this.RedirectToAction("Edit", new { index = name });
                }

                for (int i = 0; i < collection.Count; i++)
                {
                    componentView.SetProperty(collection.GetKey(i), collection[i]);
                }

                if (componentView.Instance != null)
                {
                    configuration.EnableComponent(componentView, isEnabled.Value);
                }

                // TODO: check this out, to upload the setting from external file or something ??
                foreach (string propertyIndex in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[propertyIndex];
                    if (file.ContentLength > 0)
                    {
                        string directory = Path.GetFullPath(this.Server.MapPath(new string(Path.DirectorySeparatorChar, 1)));
                        string destinationPath = componentView.UploadFile(propertyIndex, directory, file.FileName);
                        if (!string.IsNullOrEmpty(destinationPath))
                        {
                            file.SaveAs(destinationPath);
                        }
                    }
                }

                configuration.Save();
                DebugConsole.Instance.EnqueueTraceInfo(string.Format("Successfully save setting for {0}", name));

                // NOTE: when there is a corupted application on the presto manifesto, the badumna package builder will
                // try to set the current directory to point to the application base directory and never set it back
                // Should do check here
                if (!Directory.GetCurrentDirectory().Equals(HomeController.BaseDirectory))
                {
                    Directory.SetCurrentDirectory(HomeController.BaseDirectory);
                }

                return this.RedirectToAction("Edit", new { index = name });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Get the list of the germ and display it under drop down list.
        /// </summary>
        /// <param name="name">Name of the service.</param>
        /// <returns>ListGermSimple partial view.</returns>
        public ActionResult GetGermList(string name)
        {
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;

            if (configuration == null)
            {
                return Content("Failed to get the germ hosts list");
            }

            this.ViewData.Model = configuration.GermClients;
            this.ViewBag.name = name;

            // Extra check for dei server
            if (name.Equals("Dei"))
            {
                ComponentView componentView = configuration.GetComponent(name);
                if (componentView != null)
                {
                    object value;
                    componentView.GetProperty("ListenWithSsl", out value);
                    this.ViewBag.useSsl = (bool)value;
                }
            }

            return PartialView("DropDownGermsList", this.ViewData.Model);
        }

        /// <summary>
        /// Set the components back to the default value.
        /// </summary>
        /// <param name="name">>Name of the component or service.</param>
        /// <returns>Redirect to Edit action.</returns>
        public ActionResult Default(string name)
        {
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;
            if (configuration != null)
            {
                configuration.SetToDefault(name);
                return RedirectToAction("Edit", new { index = name });
            }

            return Content(string.Format("Failed to set {0} back to default value", name));
        }
    }
}

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Controllers/ServiceController.cs
//-----------------------------------------------------------------------
// <copyright file="ServiceController.cs" company="Scalify Pty Ltd">
//     Copyright (c) 2010 Scalify Pty Ltd. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

using Badumna.Package;

using Germinator;
using Germinator.Components;
using Germinator.Services;

namespace BadumnaNetworkController.Controllers
{
    /// <summary>
    /// ServiceController class shouldn't be used anymore. It should be handle it in NetworkController class.
    /// </summary>
    public class ServiceController : Controller
    {
        /// <summary>
        /// Display the status of the specific process.
        /// </summary>
        /// <param name="serviceName">Service name.</param>
        /// <param name="host">Germ host name, including the port number.</param>
        /// <param name="customName">Service custom name.</param>
        /// <returns>Return the status.aspx page.</returns>
        public ActionResult Status(string serviceName, string host, string customName)
        {
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;
            BaseService service = null;
            if (configuration != null)
            {
                this.ViewBag.ApplicationName = configuration.Name;
                service = configuration.GetService(serviceName);
            }

            if (service != null)
            {
                this.ViewData.Model = service.GetStatus(host);

                foreach (RemoteServiceProcess process in service.Instances)
                {
                    if (process.Germ.Name.Equals(host))
                    {
                        this.ViewBag.ProcessInfo = process;
                    }
                }

                if (service as PeerService != null)
                {
                    this.ViewBag.Process = this.ViewBag.ProcessInfo;                    
                }

                this.ViewBag.Service = serviceName;
                this.ViewBag.Host = host;
                this.ViewBag.CustomName = customName;
                return PartialView("Status");
            }

            return Content("Failed");
        }

        /// <summary>
        /// Remove a particular service from the control center.
        /// (Note: this can be done using an ajax request, and just return a partial view).
        /// </summary>
        /// <param name="serviceName">Service name need to be removed.</param>
        /// <returns>Redirect to network index page.</returns>
        public ActionResult Remove(string serviceName)
        {
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;
            BaseService service = null;

            if (configuration != null)
            {
                service = configuration.GetService(serviceName);
            }

            if (service != null)
            {
                // Remove the package from list
                PackageManager.Instance.RemovePacakage(serviceName);

                // Remove component from ComponentContainer
                ComponentContainer.Instance.Remove(service.Index);

                // Remove component from the current configuration
                configuration.RemoveComponent(service.Index);
            }

            return RedirectToAction("Index", "Network");
        }
    }
}

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Network/Components.cshtml
@using System.Collections;
@using Germinator.Components;
@using Germinator.Services;
@using BadumnaNetworkController;

@model IEnumerable<ComponentView>

<link href="../../Content/Site.css" rel="stylesheet" type="text/css" visible="false"/>

<div id="componentList">

    <h3>@Resources.GlobalSettings:<img src="../../Content/images/qm.png" style="width:20px;height:20px;cursor:pointer;" alt="QuestionMark" onclick="showHelp('Configuration','Components');"/></h3>
    
    <table id='Components'class="generalListTable" >
        <tr>
            <th colspan="2">
                @Resources.Module:
            </th>
        </tr>
        @foreach (var component in Model)
        {
            if (component != null)
            {
                BaseService service = component.Instance as BaseService;

                // Note: Do not display diagnostic component to the user, we don't want to change any code in
                // germinator, in case this feature will be used in the future
                if (service == null && !component.Index.Equals("Diagnostics") && !component.Index.Equals("Logging") && !component.Index.Equals("ClientListenerComponent"))
                {
                    <tr>
                        <td>
                            @Html.Encode(component.DisplayName)<br />
                        </td>
                        <td>
                            @Html.ActionLink(Resources.Change, "Edit", "Component", new { index = component.Index }, new { })
                        </td>
                    </tr>
                }
            }
        }
    </table>
</div>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Network/Create.cshtml
@using Germinator;
@using BadumnaNetworkController;

@model Configuration
@{
    ViewBag.Title = Resources.CreateNetwork;
}

<h2>@Resources.CreateNetwork <img src="../../Content/images/qm.png" style="width:20px;height:20px;cursor:pointer;" alt="QuestionMark" onclick="showHelp('Configuration','GettingStarted');"/></h2>
@Html.ValidationSummary(Resources.ErrorSummary)
@using (Html.BeginForm())
{
    <fieldset>
        <p>Welcome to Badumna Control Center.</p>
        <p>
            <label for="Name">@Resources.FriendlyName:</label>
            @Html.TextBox("Name")
            @Html.ValidationMessage("Name", "*")
        </p>
        <p>
            <label for="ProtocolHash">@Resources.ApplicationName:</label>
            @Html.TextBox("ProtocolHash")
            @Html.ValidationMessage("ProtocolHash", "*")
        </p>        
        <p>
            <input type="submit" value='@Resources.Create' />
        </p>
    </fieldset>
}

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Network/Details.cshtml
@using Germinator;
@using BadumnaNetworkController;

@model Configuration
@{
    ViewBag.Title = Model.Name;
}

<h2>@Resources.NetworkDetails<img src="../../Content/images/qm.png" style="width:20px;height:20px;cursor:pointer;" alt="QuestionMark" onclick="showHelp('Configuration','Overview');"/></h2>
<fieldset>
    <p>
        @if (ViewBag.RunningServices != null)
        {
            Html.RenderPartial("RunningServices", (object)ViewBag.RunningServices);
        }
    </p>
    <p>
        @if (Model.GermClients != null)
        {
            Html.RenderPartial("Germs", Model.GermClients);
        }
    </p>       
    <p>
        @{ Html.RenderPartial("Components", Model.Components); }
    </p>
    <p>
        @{ Html.RenderPartial("Services", Model.Components); }
    </p>
</fieldset>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Network/Germs.cshtml
@using System.Collections;
@using Germinator;
@using BadumnaNetworkController;

@model IEnumerable<GermClient>
           
<link href="../../Content/Site.css" rel="stylesheet" type="text/css" visible="false"/>

<div id="germList">
    <script type="text/javascript" language="javascript">
        var germList = new Array();
        var germsCount;
        $(function () {
            germsCount = '@(Model.Count<GermClient>())';
            for (var i = 0; i < germsCount; i++) {
                var id = "germ" + i;
                germList[i] = document.getElementById(id).getAttribute("name");
            }
        });

        $(function () {
            getMachineStatus();
        });

        function getMachineStatus() {
            var hostNames = "";
            for (var i in germList) {
                if (i == germsCount - 1) {
                    hostNames += germList[i];
                }
                else {
                    hostNames += germList[i] + ",";
                }
            }
            
            $.manageAjax.add('cacheQueue', {
                url: '@Url.Action("GetMachineStatus", "Germ")',
                data: { 'name': hostNames, 'count': germsCount },
                type: 'POST',
                success: function (response) {
                    var lines = response.split("|");
                    for (var j in lines) {
                        if (lines[j] != "" && lines[j].indexOf("Error") == -1) {
                            var tokens = lines[j].split(":");
                            var load = tokens[2].split(" ");
                            var memAvailable = tokens[3];
                            var elementName = "cpuLoad" + tokens[1];

                            var elements = document.getElementsByTagName('div');
                            var element;
                            for (var i = 0; i < elements.length; i++) {
                                var tmp = elements[i];
                                if (tmp.id == elementName) {
                                    element = elements[i];
                                    break;
                                }
                            }

                            if (element != null) {
                                if (load[0] == "N/A") {
                                    element.className = 'normalText';
                                }
                                else if (load[0] > 90.0) {
                                    element.className = 'redText';
                                }
                                else if (load[0] > 60.0) {
                                    element.className = 'yellowText';
                                }
                                else {
                                    element.className = 'greenText';
                                }
                            }

                            $("#connectionStatus" + tokens[1]).html(tokens[0]);
                            $("#cpuLoad" + tokens[1]).html(tokens[2]);
                            $("#memAvailable" + tokens[1]).html(tokens[3]);
                        }
                    }
                }
            });

            setTimeout(getMachineStatus, 300000);
        }
    </script>
    <h3>@Resources.GermsHost:<img src="../../Content/images/qm.png" style="width:20px;height:20px;cursor:pointer;" alt="QuestionMark" onclick="showHelp('Configuration','Germs');"/></h3>
    <table class="generalListTable">
        <tr>
            <th>Host name</th>
            <th>Status</th>
            <th>CPU Load</th>
            <th>Memory Available</th>
            <th></th>
        </tr>        
            @{
                int i = 0;
                foreach( var globalGerm in GerminatorFacade.Instance.GetAllGermClients())
                {
                    string id = "germ" + i;
                    string updateTag = String.Format("upd_{0}", i);
                    string itemTag = String.Format("item_{0}", i); 
                    <tr>
                        <td>
                            <label id="@id" name="@globalGerm.Name">@Html.Encode(globalGerm.Name)</label>
                        </td>
                        <td>
                            <div id="connectionStatus@(i)">N/A</div>
                        </td>
                        <td>
                            <div id="cpuLoad@(i)">N/A</div>
                        </td>
                        <td>
                            <div id="memAvailable@(i)">N/A</div>
                        </td>
                        <td align="center">            
                            @Html.ActionLink(Resources.ViewDetails, "Details", "Germ", new { name = globalGerm.Name }, null)|                        
                            <span>
                                <img id='@updateTag' src='/Content/wait16.gif' style='display: none;' alt='Updating ...' />
                                <span id='@itemTag'>
                                    @Ajax.ActionLink(
                                        Resources.Remove, 
                                        "RemoveGerm", 
                                        new { name = globalGerm.Name },
                                        new AjaxOptions() { UpdateTargetId = "germList",
                                                LoadingElementId = updateTag,
                                                OnBegin = "function(){ return $('#" + itemTag + "').hide(); }",
                                                OnComplete = "function(){ return $('#" + itemTag + "').show(); }"
                                        }
                                    )
                                </span>
                            </span>
                        </td>
                    </tr>
                    i++;
                }
            }
        <tr>
            <td colspan="5">
                @Html.ActionLink(Resources.AddGerm, "Create", "Germ")
            </td>
        </tr>
    </table>
</div>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Network/RunningServices.cshtml
@using System.Collections.Generic;
@using Germinator.Services;
@using GermServer;
@using BadumnaNetworkController;

@model Dictionary<string, RemoteServiceProcess>

<link href="../../Content/Site.css" rel="stylesheet" type="text/css" runat="server" id="styleMain" visible="false" />
<div id="runningServiceList">
    <h3>@Resources.RunningServices:<img src="../../Content/images/qm.png" style="width:20px;height:20px;cursor:pointer;" alt="QuestionMark" onclick="showHelp('Configuration','RunningServices');"/></h3>
    
    <table id='Services' class="generalListTable">
        <tr>
            <th>@Resources.ServiceName</th>
            <th>@Resources.Host</th>
            <th>@Resources.TimeOfLastPing</th>
            <th>@Resources.PingResponse</th>
            <th></th>
        </tr>
            @if (Model.Count == 0)
            {
                <tr>
                    <td colspan='5' align='center'>No services are currently running.</td>
                </tr>
            }
            else
            {
                int i = 0;
                foreach (KeyValuePair<string, RemoteServiceProcess> pair in Model)
                {
                    string updateTag = String.Format("updating_{0}", i++);
                    string updateLink = String.Format("{0}_link", updateTag);
                   <tr>
                        <td>@Html.Encode(pair.Key)</td>            
                        <td>@Html.Encode(pair.Value.Germ.Name)</td>
                        <td>@Html.Encode(string.Format("{0:g}", pair.Value.TimeOfLastPing))</td>
                        <td>@pair.Value.PingStatus</td>
                        <td>
                            @if (pair.Value.PingStatus == PingStatus.ExitWithError)
                            {
                                @Html.Encode(Resources.ShowStatus + "|")
                            }
                            else
                            {
                                @Html.ActionLink(Resources.ShowStatus, "Status", "Service", new { serviceName = ((ProcessDescription)pair.Value.Process).Name, host = pair.Value.Germ.Name, customName = pair.Key }, null)
                            }
                            
                            |<img id='@updateTag' src='/Content/wait16.gif' style='display: none;' alt='Updating ...' />
                            <span id='@updateLink'>
                                @Ajax.ActionLink(
                                    Resources.Ping,
                                    "Ping",
                                    new { serviceName = ((ProcessDescription)pair.Value.Process).Name, host = pair.Value.Germ.Name },
                                    new AjaxOptions()
                                    {
                                        UpdateTargetId = "runningServiceList",
                                        LoadingElementId = updateTag,
                                        OnBegin = "function(){ return $('#" + updateLink + "').hide(); }",
                                        OnComplete = "function(){ return $('#" + updateLink + "').show(); }"
                                    }
                                )
                            </span>
                            | @Ajax.ActionLink(
                                    Resources.KillProcess,
                                    "StopService",
                                    new { serviceName = ((ProcessDescription)pair.Value.Process).Name, germName = pair.Value.Germ.Name, redirectToHome = false },
                                    new AjaxOptions() { UpdateTargetId = "runningServiceList" })
                            | @Ajax.ActionLink(
                                    Resources.RestartService,
                                    "RestartService",
                                    new { serviceName = ((GermServer.ProcessDescription)pair.Value.Process).Name, germName = pair.Value.Germ.Name, redirectToHome = false },
                                    new AjaxOptions() { UpdateTargetId = "runningServiceList" })
                        </td>
                   </tr>
                }
            }
    </table>
</div>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Network/Services.cshtml
@using System.Collections;
@using Germinator.Components;
@using Germinator.Services;
@using BadumnaNetworkController;

@model IEnumerable<ComponentView>

<link href="../../Content/Site.css" rel="stylesheet" type="text/css" runat="server" id="styleMain" visible="false" />

<div id="serviceList">
    <h3>@Resources.AvailableServices:<img src="../../Content/images/qm.png" style="width: 20px; height: 20px; cursor: pointer;" alt="QuestionMark" onclick="showHelp('Configuration','Services');" /></h3>
    <table id='Services' class="generalListTable">
        <tr>
            <th>@Resources.ServiceName</th>
            <th></th>
        </tr>
        @foreach (var component in Model)
        {
            if (component != null)
            {
                // Note: Remove clandenstine peer service from the default services, just don't display it
                BaseService service = component.Instance as BaseService;
                if (service != null && !service.Index.Equals("ClandestinePeer"))
                {
                    <tr>
                        <td>@Html.Encode(component.DisplayName) <br /></td>
                        <td align="left">
                            @Html.ActionLink(Resources.Change, "Edit", "Component", new { index = service.Index }, new { })
                            |<a onclick="StartApplication('@service.Index');" style="cursor: pointer;"><span style="text-decoration: underline">@Resources.StartService</span></a>
                            @{
                                // Can't remove the default packages
                                string[] exclusionList = new string[] { "ClandestinePeer", "SeedPeer", "Dei", "OverloadPeer", "HttpTunneling", "StatisticsServer" };
                                if (!exclusionList.Contains(service.Index))
                                {                              
                                    @Html.Raw("|");      
                                    @Html.ActionLink(Resources.Remove, "Remove", "Service", new { serviceName = service.Index }, null)
                                }
                            }
                        </td>
                    </tr>
                }
            }
        }
    </table>
</div>