Source/ManagementTools/ControlCenter/BadumnaNetworkController/Controllers/ComponentController.cs
//-----------------------------------------------------------------------
// <copyright file="ComponentController.cs" company="Scalify Pty Ltd">
//     Copyright (c) 2010 Scalify Pty Ltd. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

using Germinator;
using Germinator.Components;
using Germinator.Services;

namespace BadumnaNetworkController.Controllers
{
    /// <summary>
    /// ComponentController class is used for displaying and modifying the properties for each individual 
    /// components and services that are available in ControlCenter. 
    /// </summary>
    public class ComponentController : Controller
    {
        /// <summary>
        /// Edit the component or service basic properties.
        /// </summary>
        /// <remarks>GET: /Component/Edit?index=service_name</remarks>
        /// <param name="index">Name of the component or service.</param>
        /// <returns>Return the details form contains component or service basic properties.</returns>
        public ActionResult Edit(string index)
        {
            // Checking for any existance of ModelState in temp data.
            if (this.TempData["ModelState"] != null && !this.ModelState.Equals(this.TempData["ModelState"]))
            {
                this.ModelState.Merge((ModelStateDictionary)this.TempData["ModelState"]);
            }

            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;
            if (configuration == null || String.IsNullOrEmpty(index))
            {
                return RedirectToAction("Index", "Home");
            }            

            ComponentView component = configuration.GetComponent(index);
            if (component == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            this.ViewData.Model = component;

            if ((component.Instance as BaseService) == null && configuration.RunningServices.Count > 0)
            {
                this.ViewBag.SettingChangeAllowed = false;
            }
            else
            {
                this.ViewBag.SettingChangeAllowed = true;
            }

            string hostname;
            int port;

            configuration.GetDeiHost(out hostname, out port);

            if (!string.IsNullOrEmpty(hostname))
            {
                this.ViewBag.DeiServerAddress = string.Format("{0}:{1}", hostname, port);
            }
            else
            {
                this.ViewBag.DeiServerAddress = null;
            }

            return View();
        }

        /// <summary>
        /// Post method from the edit component, update the component or service properties using 
        /// the submitted form received.
        /// </summary>
        /// <remarks>POST: /Component/Edit/</remarks>
        /// <param name="name">Name of the component or service.</param>
        /// <param name="isEnabled">This parameter is no longer used.</param>
        /// <param name="collection">The form collection obtained from the client.</param>
        /// <returns>Redirect to Edit action.</returns>
        /// <seealso cref="Edit(string)"/>
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit(string name, bool? isEnabled, FormCollection collection)
        {
            try
            {
                Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;
                if (configuration == null || string.IsNullOrEmpty(name))
                {
                    return RedirectToAction("Index", "Home");
                }
               
                ComponentView componentView = configuration.GetComponent(name);
                if (componentView == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                if (!isEnabled.HasValue)
                {
                    isEnabled = false;
                }

                for (int i = 0; i < collection.Count; i++)
                {
                    if (collection[i] == null)
                    {                        
                        this.ModelState.AddModelError(collection.GetKey(i), Resources.Invalid);
                    }

                    // extra checking for application name.
                    if (collection.GetKey(i) == "ApplicationName")
                    {
                        if (!InputValidationHelper.ValidateAlphanumeric(collection[i] as string))
                        {
                            this.ModelState.AddModelError(collection.GetKey(i), Resources.InvalidName);
                        }
                    }
                }

                if (!this.ModelState.IsValid)
                {
                    this.TempData["ModelState"] = this.ModelState;
                    return this.RedirectToAction("Edit", new { index = name });
                }

                for (int i = 0; i < collection.Count; i++)
                {
                    componentView.SetProperty(collection.GetKey(i), collection[i]);
                }

                if (componentView.Instance != null)
                {
                    configuration.EnableComponent(componentView, isEnabled.Value);
                }

                // TODO: check this out, to upload the setting from external file or something ??
                foreach (string propertyIndex in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[propertyIndex];
                    if (file.ContentLength > 0)
                    {
                        string directory = Path.GetFullPath(this.Server.MapPath(new string(Path.DirectorySeparatorChar, 1)));
                        string destinationPath = componentView.UploadFile(propertyIndex, directory, file.FileName);
                        if (!string.IsNullOrEmpty(destinationPath))
                        {
                            file.SaveAs(destinationPath);
                        }
                    }
                }

                configuration.Save();
                DebugConsole.Instance.EnqueueTraceInfo(string.Format("Successfully save setting for {0}", name));

                // NOTE: when there is a corupted application on the presto manifesto, the badumna package builder will
                // try to set the current directory to point to the application base directory and never set it back
                // Should do check here
                if (!Directory.GetCurrentDirectory().Equals(HomeController.BaseDirectory))
                {
                    Directory.SetCurrentDirectory(HomeController.BaseDirectory);
                }

                return this.RedirectToAction("Edit", new { index = name });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Get the list of the germ and display it under drop down list.
        /// </summary>
        /// <param name="name">Name of the service.</param>
        /// <returns>ListGermSimple partial view.</returns>
        public ActionResult GetGermList(string name)
        {
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;

            if (configuration == null)
            {
                return Content("Failed to get the germ hosts list");
            }

            this.ViewData.Model = configuration.GermClients;
            this.ViewBag.name = name;

            // Extra check for dei server
            if (name.Equals("Dei"))
            {
                ComponentView componentView = configuration.GetComponent(name);
                if (componentView != null)
                {
                    object value;
                    componentView.GetProperty("ListenWithSsl", out value);
                    this.ViewBag.useSsl = (bool)value;
                }
            }

            return PartialView("DropDownGermsList", this.ViewData.Model);
        }

        /// <summary>
        /// Set the components back to the default value.
        /// </summary>
        /// <param name="name">>Name of the component or service.</param>
        /// <returns>Redirect to Edit action.</returns>
        public ActionResult Default(string name)
        {
            Configuration configuration = this.Session[HomeController.ConfigurationSessionKey] as Configuration;
            if (configuration != null)
            {
                configuration.SetToDefault(name);
                return RedirectToAction("Edit", new { index = name });
            }

            return Content(string.Format("Failed to set {0} back to default value", name));
        }
    }
}

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Controllers/PackageController.cs
//-----------------------------------------------------------------------
// <copyright file="PackageController.cs" company="Scalify Pty Ltd">
//     Copyright (c) 2010 Scalify Pty Ltd. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using System.IO;
using System.Web;
using System.Web.Mvc;

using Badumna.Package;

using Germinator;
using System.Collections.Generic;

namespace BadumnaNetworkController.Controllers
{
    /// <summary>
    /// PackageController class display the service package details information, and also used to update 
    /// the package for the default services if neccessary.
    /// </summary>
    public class PackageController : Controller
    {       
        /// <summary>
        /// Display the details information about a particular package for a particular service.
        /// </summary>
        /// <remarks> GET: /Package/Details/ </remarks>
        /// <param name="name">The name of the package.</param>
        /// <param name="displayName">The display name of the service (i.e. service name may be different with display name).</param>
        /// <returns>The package details information.</returns>
        public ActionResult Details(string name, string displayName)
        {
            if (string.IsNullOrEmpty(name))
            {
                return RedirectToAction("Index", "Network");
            }

            this.ViewBag.index = name.Contains("Dei") ? "Dei" : name;
            this.ViewBag.DisplayName = displayName;
            ViewData.Model = GerminatorFacade.Instance.GetPackage(name);
            return View();
        }

        /// <summary>
        /// Post method for details is used to update the current package with the newer package, upload
        /// two files (manifest.xml and the new package itself), this function will be available only for 
        /// default services package (i.e. PublicPeer, Dei, HttpTunneling and Overload peer).
        /// </summary>
        /// <param name="displayName">The display name of the service.</param>
        /// <returns>Redirect to package details information.</returns>
        /// <seealso cref="Details(string,string)"/>
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Details(string displayName, IEnumerable<HttpPostedFileBase> files)
        {
            // TODO : Check the current package version has to be newer than the previous file
            string appPath = Request.PhysicalApplicationPath;
            string saveDir = @"\Services\";
            string packageName = string.Empty;

            foreach (HttpPostedFileBase file in files)
            {
                if (file.ContentLength > 0)
                {
                    // Note: Manifest.xml has to be uploaded first
                    if (file.FileName.Equals(Manifest.DefaultFileName))
                    {
                        Manifest manifest = Manifest.Load(file.InputStream);
                        packageName = manifest.ApplicationName;
                        saveDir += packageName + @"\";
                        if (!Directory.Exists(appPath + saveDir))
                        {
                            DebugConsole.Instance.EnqueueTraceInfo(string.Format("Failed to update {0} package, the service doesn't exist", displayName));
                            return Content("Failed to update the package, the service doesn't exist");
                        }
                    }

                    string fileName = file.FileName;
                    string savePath = appPath + saveDir + fileName;
                    file.SaveAs(savePath);
                }
            }

            DebugConsole.Instance.EnqueueTraceInfo(string.Format("Update {0} package successfully", displayName));
            return RedirectToAction("Details", new { name = packageName, displayName = displayName });
        }
    }
}

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Component/DropDownGermsList.cshtml
@using System.Collections;

<script type="text/javascript" language="javascript">
    function OnPropertyChange() {
        var element = document.getElementById("CertificateOptions");
        var value = element.options[element.selectedIndex].value;
        var passField = document.getElementById("CertificatePassphrase");

        if (value == "Custom certificate") {
            passField.disabled = false;
            passField.style.backgroundColor = "white";
        }
        else {
            passField.disabled = true;
            passField.style.backgroundColor = "grey";
        }
    }
</script>

<div>
    <table>
        <tr>
            <td colspan='2'>
                <label>Start @Html.Encode(ViewBag.name) service</label>
            </td>
        </tr>
        <tr>
            <td>
                Service Name:
            </td>
            <td>
                @Html.TextBox("ServiceName", (string)ViewBag.name, new {style = "background:white;color:black;" })
            </td>
        </tr>
        <tr>
            <td>
                Start service on:
            </td>
            <td>
                @Html.DropDownList("GermList", new SelectList(Model), new { style = "background:white;color:black;" })
            </td>
        </tr>
        @if (ViewBag.name.Equals("Dei") && (bool)ViewBag.useSsl)
        {
        <tr>
            <td>
                Certificate type:
            </td>
            <td>
                @{
                    string[] certificateType = new string[] { "Autogenerate certificate", "Custom certificate" };
                    IEnumerable<string> cert = certificateType.AsEnumerable<string>();
                }
                @Html.DropDownList("CertificateOptions", new SelectList(cert), new { style = "background:white;color:black;", onchange = "OnPropertyChange();" })
            </td>
        </tr>
        <tr>
            <td>
                Certificate passphrase:
            </td>
            <td>
                @Html.Password("CertificatePassphrase", null, new { style = "background:grey;color:black;", disabled = "true" })
            </td>
        </tr>
        }
    </table>
</div>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Component/Edit.cshtml
@using Germinator.Components;
@using Germinator.Services;
@using BadumnaNetworkController;

@model ComponentView

@{
    ViewBag.Title = Model.DisplayName;
}

<script type="text/javascript">    
    function toogleView(itemName) {
        var updateForm = document.getElementById(itemName);
        if (updateForm != null && updateForm.style.display == 'none') {
            updateForm.style.display = 'table-row';
        }
        else {
            updateForm.style.display = 'none';
            var textbox = document.getElementById(itemName + "-tb");
            textbox.value = 0;
            onPropertyChange();
        }
    }

    function toogleDeiView() {
        var tr = document.getElementsByTagName('tr');
        for (var i = 0; i < tr.length; i++) {
            if (tr[i].getAttribute('name')) {
                if (tr[i].style.display == 'none') {
                    tr[i].style.display = 'table-row';
                }
                else {
                    tr[i].style.display = 'none';
                }
            }
        }
    }

    function onPropertyChange(id) {
        var settingChangeAllowed = '@ViewBag.SettingChangeAllowed';

        if (id == "ParticipationValidityPeriod") {
            if (document.getElementById(id).value <= 0) {
                var txt = "<p>The Participation validity period must be greater than 0. </p>";
                $.prompt(txt, {
                    callback: onPropertyChangeCallback,
                    buttons: { Ok: false }
                });

                return;
            }
        }
        else if (id == "MaintenanceTaskIntervalSeconds") {
            if (document.getElementById(id + "-tb").value <= 0) {
                var txt = "<p>Maintenance task interval must be greater than 0. </p>";
                $.prompt(txt, {
                    callback: onPropertyChangeCallback,
                    buttons: { Ok: false }
                });

                return;
            }
        }
        else if (id == "ApplicationName") {
            if (!validateAlphanumeric(document.getElementById(id).value)) {
                var txt = "<p>Invalid name, name should only consisting of alphanumeric, - or _ only.</p>";
                $.prompt(txt, {
                    buttons: { Ok: false }
                });

                return;
            }
        }


        if (settingChangeAllowed == "False") {
            var txt = "<p>There are currently running services, changing the global setting my causing an inconsistency in Badumna network configuration";
            txt += "<br/>Are you sure want to change the setting ? </p>";
            $.prompt(txt, {
                callback: onPropertyChangeCallback,
                buttons: { Ok: true, Cancel: false }
            });
        }
        else {
            var form = document.getElementById('form');
            form.submit();
        }
    }

    function onPropertyChangeCallback(v) {
        if (v) {
            var form = document.getElementById('form');
            form.submit();
        }
        else {
            window.location.reload(true);
        }
    }

    function onDefaultButton() {
        var settingChangeAllowed = '@ViewBag.SettingChangeAllowed';
        if (settingChangeAllowed == "False") {
            var txt = "<p>There are currently running services, changing the global setting my causing an inconsistency in Badumna network configuration";
            txt += "<br/>Are you sure want to change the setting back to default value? </p>";
            $.prompt(txt, {
                callback: onDefaultButtonCallback,
                buttons: { Ok: true, Cancel: false }
            });
        }
        else {
            var url = '@Url.Action("Default", new { name = Model.Index })';
            location.href = url;
        }
    }

    function onDefaultButtonCallback(v) {
        if (v) {
            var url = '@Url.Action("Default", new { name = Model.Index })';
            location.href = url;
        }
    }    
</script>

@if (Model.Index.Equals("Dei") || Model.Index.Equals("SeedPeer") || Model.Index.Equals("OverloadPeer") || Model.Index.Equals("HttpTunneling"))
{
    <h2>'@Model.DisplayName' Settings <img src="../../Content/images/qm.png" style="width:20px;height:20px;cursor:pointer;" alt="QuestionMark" onclick="showHelp('Configuration','@Model.Index','jqiwide');"/></h2>
}
else
{
    <h2>'@Model.DisplayName' Settings </h2>
}
    

@using (Html.BeginForm("Edit", "Component", new { name = Model.Index }, FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
{
    <fieldset>
        @Html.ValidationSummary()
        <table>
            @{
                // Check whether the model is a component or services 
                bool isComponent = false;
                BaseService service = Model.Instance as BaseService;

                if (service == null)
                {
                    isComponent = true;
                }

                if (isComponent)
                {
                    // Handle a component (Note: will remove the logging component from the component and leave it as subcomponent)
                    // Handle Badumna Component as a special case
                    Html.RenderPartial("EditComponent", Model);
                }
                else
                {
                    Html.RenderPartial("EditService", Model);
                }
            }
        </table>
    </fieldset>
}    

<div>
    <p>@Html.ActionLink(Resources.BackToHome, "Index", "Network")</p>
</div>

Source/ManagementTools/ControlCenter/BadumnaNetworkController/Views/Component/EditService.cshtml
@using Germinator.Components;
@using Germinator.Services;
@using BadumnaNetworkController;

@model ComponentView

@{
    // Do the check for default services
    bool usingDei = false;
    bool isDefaultService = false;
    string[] defaultServices = new string[] { "OverloadPeer", "SeedPeer", "Dei", "HttpTunneling", "StatisticsServer" };
    string[] exlusionList = new string[] { 
        "CompatibleHosts", 
        "MaintenanceTaskIntervalSeconds", 
        "MaximumNumberOfInstances", 
        "UseDei",
        "DeiServerAddress",
        "DeiUsername",
        "DeiPassword",
        "SslConnection",
        "PublicKeyValidityPeriod"};

    foreach (string serviceName in defaultServices)
    {
        if (Model.Index.Equals(serviceName))
        {
            isDefaultService = true;
            break;
        }
    }

    foreach (var item in Model)
    {
        // Do not display the unrelevant options.
        if (!exlusionList.Contains(item.Index)
            && !(isDefaultService && item.Index.Equals("ProcessArguments"))
            && !(Model.Index.Equals("OverloadPeer") && item.Index.Equals("NewNetwork")))
        {
            <tr>
                <td>@Html.Encode(item.Name)</td>
                <td>
                    @switch (item.Type)
                    {
                        case PropertyType.File:
                            @Html.FileBox(item.Index, item.Value);
                            break;
                        case PropertyType.String:
                            @Html.TextBox(item.Index, item.Value, new { onchange = "onPropertyChange('" + item.Index + "');" });
                            break;
                        case PropertyType.Int:
                            @Html.TextBox(item.Index, item.Value.ToString(), new { onchange = "onPropertyChange('" + item.Index + "');" });
                            break;
                        case PropertyType.Bool:
                            @Html.CheckBox(item.Index, (bool)item.Value, new { onclick = "onPropertyChange('" + item.Index + "');" });
                            break;
                        case PropertyType.StringList:
                            @Html.ListBox(item.Index, new MultiSelectList((IEnumerable<string>)item.PossibleValues, (string[])item.Value), new { onchange = "onPropertyChange('" + item.Index + "');" });
                            break;
                        case PropertyType.StringOption:
                            int index = 0;
                            for (int i = 0; i < item.PossibleValues.Count(); i++)
                            {
                                string value = item.PossibleValues.ElementAt<string>(i);
                                if (value.Equals(item.Value))
                                {
                                    index = i;
                                    break;
                                }
                            }
                            @Html.DropDownList(item.Index, new SelectList(item.PossibleValues, item.PossibleValues.ElementAt<string>(index)), new { onchange = "onPropertyChange('" + item.Index + "');" });
                            break;
                        case PropertyType.SubComponent:
                            @Html.ActionLink(Resources.EditSubComponent, "Edit", new { index = item.Index });
                            break;
                    }
                </td>
            </tr>
        }
        else if(item.Index.Equals("MaintenanceTaskIntervalSeconds") && Model.Instance is PeerService)
        {
            <tr>
                <td>@Html.Encode(item.Name)</td>
                <td>
                    @{
                        bool enableMaintenanceTask = (int)item.Value > 0 ? true : false;
                        if (enableMaintenanceTask)
                        {
                            <input type="checkbox" name="cb@item.Index" checked="checked" onchange="toogleView('@item.Index');" />
                        }
                        else
                        {
                            <input type="checkbox" name="cb@item.Index" onchange="toogleView('@item.Index');" />
                        }

                        string style = "display:" + (enableMaintenanceTask ? "table-row" : "none");
                     }
                </td>
            </tr>
            <tr id="@item.Index" style="@style">
                <td>
                    <label>Monitor frequency (sec)</label>
                </td>
                <td>
                    @Html.TextBox(item.Index, item.Value.ToString(), new { onchange = "onPropertyChange('" + item.Index + "');", id = string.Format("{0}-tb", item.Index) })
                </td>
            </tr>
        }
        else if(item.Index.Equals("UseDei"))
        {
            // Note : Dei module is used for the overload peer and seed peer only, the arbitration service should has their own mechanism 
            // how to handle when the deiserver is used.
            usingDei = (bool)item.Value;
            <tr>
                <td>@Html.Encode(item.Name)</td>
                <td>
                    @Html.CheckBox(item.Index, (bool)item.Value, new { onclick = "toogleDeiView();onPropertyChange('" + item.Index + "');" })
                </td>
            </tr>
        }
        else if(item.Index.Equals("DeiServerAddress") 
            || item.Index.Equals("DeiUsername")
            || item.Index.Equals("DeiPassword") 
            || item.Index.Equals("SslConnection"))
        {
            string style = "display:" + (usingDei ? "table-row" : "none");
            <tr name="Dei" style="@style">
                <td>@Html.Encode(item.Name)</td>
                <td>
                    @switch(item.Type)
                    {
                        case PropertyType.String:
                            if(item.Index.Equals("DeiPassword"))
                            {
                                @Html.Password(item.Index, item.Value, new { onchange = "onPropertyChange('" + item.Index + "');" })    
                            }
                            else if (item.Index.Equals("DeiServerAddress") && ViewBag.DeiServerAddress != null)
                            {
                                @Html.TextBox(item.Index, (string)ViewBag.DeiServerAddress, new { onchange = "onPropertyChange('" + item.Index + "');" })
                            }
                            else
                            {
                                @Html.TextBox(item.Index, item.Value, new { onchange = "onPropertyChange('" + item.Index + "');" })
                            }
                            break;
                        case PropertyType.Bool:
                            @Html.CheckBox(item.Index, (bool)item.Value, new { onclick = "onPropertyChange('" + item.Index + "');" })
                            break;     
                    }
                </td>             
            </tr>
        }
    }
}

<tr>
    <td>
            @Resources.PackageDetails:
    </td>
    <td>
            @Html.ActionLink(Html.Encode(Model.Index), "Details", "Package", new { name = Model.Index, displayName = Model.DisplayName }, null)
    </td>
</tr>
<tr>
    <td colspan="2">
        <a onclick="StartApplication('@Model.Index');" style="cursor: pointer;"><span style="text-decoration: underline"> @Resources.StartService</span></a> 
        |
        <a onclick="onDefaultButton();" style="cursor: pointer;"><span style="text-decoration: underline"> @Resources.Default</span></a>
    </td>
</tr>